// Source of raw/handbook/tide-almanac.pdf — a long document (60+ pages), so
// the "prefer pdftotext for anything over ~40 pages" branch of /ingest and the
// `pages:` range have something real to work on.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 20mm, numbering: "1")
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")

#align(center)[
  #text(size: 20pt)[Tide almanac of the Kestrel Islands] \
  #v(4pt)
  #text(size: 11pt, style: "italic")[Tide office, Fenmouth — invented material]
]
#v(10pt)
One page per week of the year. The heights are above chart datum; the age of
the tide is two days throughout.

#for week in range(1, 61) {
  pagebreak()
  heading(level: 1, text(size: 14pt)[Week #week])
  let phase = if calc.rem(week, 4) == 1 { "new moon, springs from day 3" } else if calc.rem(week, 4) == 3 { "full moon, springs from day 3" } else { "quarter, neaps" }
  [Moon: #phase. Mean range 3.4 m, spring range 5.1 m, neap range 1.7 m.]
  table(
    columns: (auto, auto, auto, auto),
    align: (left, center, center, left),
    table.header([*Day*], [*HW*], [*LW*], [*Ovray Cove*]),
    ..for day in range(1, 8) {
      let hw = 3 + calc.rem(week * 7 + day, 9)
      ([Day #day], [#{hw}:#{calc.rem(day * 50, 60)} h], [#{calc.rem(hw + 6, 12)}:#{calc.rem(day * 50, 60)} h],
       [#if calc.rem(week, 4) == 1 { "closed at low water" } else { "open" }])
    }
  )
  [The stream in the gap between Torvig and Little Kestrel follows the tide
   with a lag of about twenty minutes and reaches 3.1 knots at springs.]
}
