// Source of raw/handbook/kestrel-handbook.pdf — a four-page PDF with a real
// text layer, the ordinary case for a `type: pdf` source. Generated by
// scripts/make_testdata.py; do not edit the PDF, edit this.
//
// Two things here exist for /ingest to have an opinion about:
//   - a raster figure on page 3, which is worth showing on a card;
//   - the harbour office mark in the running header, which is on every page and
//     is furniture rather than a figure. A picture repeated on four pages must
//     be offered once, or every deck grows a logo card.
#let office-mark = image("../raw/images/office-mark.png", width: 12mm)
#set page(
  paper: "a4",
  margin: 25mm,
  numbering: "1",
  header: context {
    set text(size: 8pt)
    grid(columns: (1fr, auto), align(left + horizon)[Torvig harbour office], office-mark)
  },
)
#set text(font: "Libertinus Serif", size: 11pt, lang: "en")
#set par(justify: true)
#show heading.where(level: 1): it => block(above: 0pt, below: 14pt, text(size: 18pt, it.body))

#align(center)[
  #text(size: 24pt)[The Kestrel Islands Handbook] \
  #v(4pt)
  #text(size: 12pt, style: "italic")[Harbour office, Torvig — invented material]
]
#v(20pt)

= 1 The archipelago

The Kestrel Islands are an archipelago of five inhabited islands in the Ashwind
Sea, roughly 400 km from the nearest mainland harbour. They are the rim of a
drowned volcanic crater; the crater floor between them, the Kestrel Deep,
reaches 890 m at its deepest sounding.

#table(
  columns: (auto, auto, auto, auto),
  align: (left, right, right, left),
  table.header([*Island*], [*Area (km²)*], [*Inhabitants*], [*Main settlement*]),
  [Torvig], [410], [3200], [Torvig Harbour],
  [Little Kestrel], [96], [840], [Fenmouth],
  [Skarn], [155], [210], [Skarn Landing],
  [Ovray], [62], [115], [Ovray Cove],
  [Bellhorn], [18], [0], [lighthouse only],
)

Torvig has the only deep-water pier of the archipelago. Everything that arrives
arrives there first and is redistributed by the mail boat.

#pagebreak()

= 2 The tide

The tide of the Ashwind Sea is semidiurnal: two high waters and two low waters
in a tidal day of 24 h 50 min. Every high water therefore arrives about fifty
minutes later than the one on the day before.

The tidal range is the height of high water minus the height of low water. At
Torvig Harbour the mean range is 3.4 m, the spring range 5.1 m and the neap
range 1.7 m — the spring range is exactly three times the neap range.

Between low water and high water the water rises for six hours, and the rise is
not even. The tide office teaches the rule of twelfths: one, two, three, three,
two and one twelfth of the range in the six successive hours. Half the range is
reached after three hours.

Spring tides occur two days after new moon and two days after full moon, twice
in a synodic month of 29.5 days. That two-day lag is the age of the tide.

#pagebreak()

= 3 The flag signal code

#figure(
  image("../raw/images/tide-chart.png", width: 80%),
  caption: [The rule of twelfths, as posted in the harbour office],
)

Before the radio link, the harbours talked to each other with flags from the
signal masts. Six flags are in use:

#list(
  [Grey — mail boat sighted],
  [Blue — pilot requested],
  [Red — harbour closed, do not enter],
  [White — doctor needed on the island],
  [Black — death in the settlement],
  [Yellow — fresh water short],
)

A flag is valid only while it is hoisted; lowering it is the cancellation. Two
flags on one mast are read from the top down, and the upper flag is the more
urgent message. White over black is forbidden. A flag at half mast means
"understood, help is on the way".

#pagebreak()

= 4 Approaching the harbours

Ovray Cove dries out below 1.2 m above chart datum. Low water at springs is
0.3 m, at neaps 1.6 m, so the cove is unreachable at low water springs and
usable throughout the neaps. Boats bound for Ovray Cove plan their arrival
within two hours either side of high water.

All heights on the charts are given above chart datum, the lowest astronomical
tide. The soundings are a worst case: the real depth is almost always greater
than the chart says.
