// Source of raw/web/harbour-plan.png — the picture the local web fixture shows
// with an <img> tag. Generated by scripts/make_testdata.py.
//
// The third place a picture can come from: on a page /ingest fetched. It has to
// be downloaded (figures.py fetch) before it can be judged.
#set page(width: 160mm, height: 90mm, margin: 6mm, fill: rgb("#fbfaf7"))
#set text(font: "Libertinus Serif", size: 9pt, lang: "en")

#align(center)[#text(size: 13pt, weight: "bold")[Torvig Harbour — the two quays]]
#v(3mm)

#let quay(label, note, y, h) = {
  place(dy: y, rect(width: 90mm, height: h, fill: rgb("#dce7f5"), stroke: 0.5pt + rgb("#4a5568")))
  place(dy: y + 2mm, dx: 3mm, text(size: 9pt, weight: "bold")[#label])
  place(dy: y + 7mm, dx: 3mm, text(size: 8pt)[#note])
}

#box(width: 148mm, height: 62mm, {
  place(rect(width: 148mm, height: 62mm, fill: rgb("#eef3fa")))
  quay("High quay", "Above every recorded surge. Mail boat berths here.", 4mm, 16mm)
  quay("Low quay", "Floods at warning stage red. Gear off at amber.", 26mm, 16mm)
  place(dy: 48mm, dx: 3mm, text(size: 8pt, style: "italic")[
    Signal mast at the head of the high quay #sym.arrow.r visible from the Deep
  ])
  place(dx: 96mm, dy: 4mm, box(width: 48mm, height: 44mm, stroke: 0.5pt + rgb("#4a5568"))[
    #align(center + horizon)[#text(size: 9pt)[Kestrel Deep \ #text(size: 7pt)[open water]]]
  ])
})
