// Source of raw/images/harbour-noticeboard.jpg — rendered to PNG and then
// converted, so the fixture holds a JPEG as well as a PNG. It is deliberately
// photo-like: a board on a wall, shot slightly off-square, the way a phone
// picture of a notice in a harbour office looks.
// Generated by scripts/make_testdata.py (only where a JPEG converter exists).
#set page(width: 160mm, height: 120mm, margin: 0pt, fill: rgb("#6f6a60"))
#set text(font: "Libertinus Serif", lang: "en")

#place(center + horizon)[
  #rotate(-1.2deg)[
    #box(
      width: 132mm,
      height: 96mm,
      fill: rgb("#f3efe4"),
      stroke: 3pt + rgb("#4a3f2f"),
      inset: 9mm,
    )[
      #align(center)[
        #text(size: 16pt, weight: "bold")[HARBOUR OFFICE TORVIG] \
        #v(1mm)
        #text(size: 10pt, style: "italic")[Notice to all masters — please read]
      ]
      #v(4mm)
      #line(length: 100%, stroke: 0.8pt)
      #v(3mm)

      #text(size: 10pt)[
        *1.* The red flag on the signal mast means the harbour is closed. Do not
        enter, and do not call the pilot. \
        #v(1.5mm)
        *2.* Ovray Cove dries out below 1.2 m. Plan your arrival within two
        hours either side of high water. \
        #v(1.5mm)
        *3.* The mail boat sails Monday and Thursday at 07:00 from the
        deep-water pier. It waits for the tide, not for you. \
        #v(1.5mm)
        *4.* Fresh water is short from day 5. The yellow flag will be hoisted
        while it lasts.
      ]

      #v(4mm)
      #align(right)[#text(size: 9pt, style: "italic")[The harbour master]]
    ]
  ]
]
