// Source of raw/images/office-mark.png — the harbour office mark that sits in
// the running header of every page of the handbook. Generated by
// scripts/make_testdata.py.
//
// It exists so /ingest has a picture that is *not* a figure: the same raster on
// four pages is furniture, and offering it four times would grow a logo card in
// every deck. figures.py reports it once, with how many pages it appeared on.
#set page(width: 18mm, height: 12mm, margin: 1mm, fill: white)
#set text(font: "Libertinus Serif", size: 5pt)
#align(center + horizon)[
  #box(width: 15mm, height: 9mm, stroke: 0.4pt)[
    #align(center + horizon)[TORVIG \ HARBOUR OFFICE]
  ]
]
