// Source of raw/field-notes/diagrams/signal-flags.png — the picture
// raw/field-notes/chart-notes.md links to with a *relative* markdown link.
// Generated by scripts/make_testdata.py.
//
// This is the fourth place a picture can come from: not a file the folder glob
// picks up on its own, but one a document points at. /ingest has to follow the
// link relative to the file that made it.
#set page(width: 150mm, height: 70mm, margin: 6mm, fill: rgb("#fbfaf7"))
#set text(font: "Libertinus Serif", size: 9pt, lang: "en")

#align(center)[#text(size: 13pt, weight: "bold")[The six flags, and how they are read]]
#v(4mm)

#let flag(fill, stripe, name, meaning) = stack(
  dir: ttb,
  spacing: 1.5mm,
  box(width: 18mm, height: 12mm, stroke: 0.5pt + rgb("#4a5568"), fill: fill, {
    if stripe { place(dy: 4mm, rect(width: 18mm, height: 4mm, fill: rgb("#fbfaf7"))) }
  }),
  align(center, text(size: 8pt, weight: "bold")[#name]),
  align(center, text(size: 7pt)[#meaning]),
)

#grid(
  columns: (1fr,) * 3,
  rows: 2,
  gutter: 5mm,
  flag(rgb("#c2251b"), false, "Red", "Harbour closed"),
  flag(rgb("#f0c000"), false, "Yellow", "Quarantine aboard"),
  flag(rgb("#5b7fb5"), false, "Blue", "Mail boat expected"),
  flag(rgb("#3a7d44"), false, "Green", "Free passage"),
  flag(rgb("#141414"), false, "Black", "Surge warning"),
  flag(rgb("#c2251b"), true, "Red barred", "Answer, message received"),
)
