// Source of raw/handbook/tide-tables-scan.pdf. This is rendered to PNG first
// and the images are then wrapped in a PDF, so the result has no text layer —
// a scan, the case /ingest has to look at instead of extracting.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 22mm)
#set text(font: "Libertinus Serif", size: 11pt, lang: "en")

#align(center)[
  #text(size: 17pt)[Tide table — Torvig Harbour] \
  #text(size: 10pt, style: "italic")[Tide office, Fenmouth · heights above chart datum]
]
#v(14pt)

#table(
  columns: (auto, auto, auto, auto, auto),
  align: (left, center, center, center, center),
  table.header([*Day*], [*HW 1*], [*LW 1*], [*HW 2*], [*LW 2*]),
  [1 (new moon)], [03:12 / 4.8 m], [09:24 / 0.6 m], [15:38 / 4.9 m], [21:50 / 0.5 m],
  [2], [04:02 / 5.0 m], [10:14 / 0.4 m], [16:28 / 5.1 m], [22:40 / 0.3 m],
  [3 (springs)], [04:52 / 5.1 m], [11:04 / 0.3 m], [17:18 / 5.1 m], [23:30 / 0.3 m],
  [4], [05:42 / 4.9 m], [11:54 / 0.5 m], [18:08 / 4.8 m], [--],
  [5], [06:32 / 4.5 m], [12:44 / 0.8 m], [18:58 / 4.4 m], [00:20 / 0.7 m],
  [6], [07:22 / 4.0 m], [13:34 / 1.1 m], [19:48 / 3.9 m], [01:10 / 1.0 m],
  [7], [08:12 / 3.5 m], [14:24 / 1.4 m], [20:38 / 3.4 m], [02:00 / 1.3 m],
  [8 (quarter)], [09:02 / 3.0 m], [15:14 / 1.6 m], [21:28 / 2.9 m], [02:50 / 1.6 m],
)

#v(10pt)
Ovray Cove dries out below 1.2 m. On days 1 to 4 the cove is unreachable around
low water; from day 6 it can be entered at any state of the tide.

#pagebreak()

#align(center)[#text(size: 17pt)[Tide table — Ovray Cove]]
#v(14pt)

#table(
  columns: (auto, auto, auto),
  align: (left, center, left),
  table.header([*Day*], [*Window around HW*], [*Note*]),
  [1 (new moon)], [13:38 -- 17:38], [morning window too short],
  [2], [14:28 -- 18:28], [],
  [3 (springs)], [15:18 -- 19:18], [strongest stream in the entrance],
  [4], [16:08 -- 20:08], [],
  [5], [16:58 -- 20:58], [],
  [6], [all day], [range below 2 m],
  [7], [all day], [],
  [8 (quarter)], [all day], [neaps],
)

#v(10pt)
The windows are two hours either side of high water. Add the age of the tide of
two days when working from the moon phase rather than from this table.
