// Source of raw/images/tide-chart.png — an infographic: boxes, arrows and
// labels that only make sense as a picture. OCR turns this kind of thing into
// word salad, which is why /ingest is told to look at it instead.
// Generated by scripts/make_testdata.py.
//
// This is the raster /ingest looks at. The picture the demo *cards* print is
// figures/island-images/tide-chart.svg — committed rather than generated, so a
// fresh checkout can run pytest before make_testdata.py ever has.
#set page(width: 200mm, height: 120mm, margin: 10mm, fill: rgb("#fbfaf7"))
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")

#let box-step(fill, title, body) = box(
  fill: fill,
  stroke: 0.6pt + rgb("#4a5568"),
  radius: 3pt,
  inset: 7pt,
  width: 42mm,
)[
  #text(weight: "bold", size: 10pt)[#title] \
  #v(2pt)
  #text(size: 9pt)[#body]
]

#align(center)[#text(size: 15pt, weight: "bold")[The rule of twelfths]]
#v(2pt)
#align(center)[#text(size: 9pt, style: "italic")[How the range is distributed over the six hours of the flood]]
#v(8pt)

#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 6mm,
  box-step(rgb("#e8eef7"), "Hour 1 + 2", "1/12 and 2/12 of the range — the water barely moves"),
  box-step(rgb("#dce7f5"), "Hour 3 + 4", "3/12 each — half the range is passed after hour 3"),
  box-step(rgb("#e8eef7"), "Hour 5 + 6", "2/12 and 1/12 — the rise runs out towards high water"),
)

#v(6mm)

#align(center)[
  #box(width: 150mm)[
    #stack(
      dir: ltr,
      spacing: 2mm,
      ..for (i, twelfth) in ((1, "1/12"), (2, "2/12"), (3, "3/12"), (4, "3/12"), (5, "2/12"), (6, "1/12")) {
        let heights = (6mm, 12mm, 18mm, 18mm, 12mm, 6mm)
        ((
          stack(
            dir: ttb,
            spacing: 1.5mm,
            box(width: 22mm, height: 22mm)[
              #align(bottom + center)[
                #text(size: 8pt)[#twelfth] \
                #rect(width: 22mm, height: heights.at(i - 1), fill: rgb("#5b7fb5"), stroke: none)
              ]
            ],
            align(center, text(size: 8pt)[hour #i]),
          )
        ),)
      }
    )
  ]
]

#v(5mm)
#align(center)[
  #text(size: 9pt)[Low water #box(width: 6mm)[#line(length: 100%, stroke: 0.8pt)] #sym.arrow.r six hours #box(width: 6mm)[#line(length: 100%, stroke: 0.8pt)] #sym.arrow.r High water]
]
#v(3mm)
#align(center)[#text(size: 8pt, style: "italic")[Torvig Harbour: mean range 3.4 m · springs 5.1 m · neaps 1.7 m]]
