// Source of tests/fixtures/zotero/storage/KESTREL03/ferry-statistics.pdf —
// the attachment of the one library item that sits in the *other* collection,
// so a --collection run has something it must leave alone.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 25mm)
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")

#align(center)[
  #text(size: 14pt)[Ferry statistics of the mainland ports] \
  #v(4pt)
  #text(size: 10pt)[Jonas Skarn · Port authority report, November 2022]
]
#v(12pt)

The mainland ports handled 214 000 passengers in the reporting year, of which
1 900 travelled onwards to the Kestrel Islands. The archipelago route is served
by the mail boat only; there is no passenger ferry.

#table(
  columns: (auto, auto, auto),
  align: (left, right, right),
  table.header([*Route*], [*Sailings*], [*Passengers*]),
  [Mainland -- Torvig Harbour], [104], [1900],
  [Mainland -- northern ports], [1240], [186000],
  [Coastal service], [820], [26100],
)

Cancellations on the archipelago route are almost entirely weather-related:
fog over the Kestrel Deep accounts for eleven of the fourteen sailings lost.
