// Source of the PDF attachment in the fake Zotero library
// (tests/fixtures/zotero/storage/KESTREL01/). A short paper with a text layer,
// so zotero_ingest.py can pull the text out with pdftotext.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 25mm)
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")
#set par(justify: true)

#align(center)[
  #text(size: 15pt)[Currents in the Ashwind Sea: a first survey] \
  #v(5pt)
  #text(size: 10pt)[Marek Ovray and Sanne Torvig] \
  #text(size: 9pt, style: "italic")[Journal of Invented Oceanography, 2019]
]
#v(14pt)

*Abstract.* We report the first systematic measurements of the currents around
the Kestrel Islands. The tidal stream through the gap between Torvig and Little
Kestrel reaches 3.1 knots at springs and reverses within twenty minutes of high
water. Over the Kestrel Deep the residual current is an order of magnitude
weaker and runs consistently to the south-west.

= 1 Method

Twelve drifters were released over eight tidal cycles from the deep-water pier
at Torvig Harbour and recovered at Fenmouth, Skarn Landing and, twice, on the
rocks north of Bellhorn. Positions were logged every ten minutes.

= 2 Results

The stream in the gap follows the tide with a lag of about twenty minutes; the
maximum of 3.1 knots coincides with the third and fourth hour of the flood, as
the rule of twelfths predicts. In the entrance to Ovray Cove the stream never
exceeded 1.4 knots, which is why the cove can be entered at all.

Over the Kestrel Deep the residual is 0.2 knots to the south-west and does not
follow the tide. We attribute it to the prevailing ashwind rather than to the
tide itself.

= 3 Conclusion

For navigation the practical consequence is the twenty-minute lag: the stream
in the gap still runs against a boat that left Torvig Harbour exactly at high
water. Departures are best planned twenty minutes late rather than early.
