// Source of tests/fixtures/zotero/storage/KESTREL04/signal-code-offprint.pdf —
// a PDF filed in Zotero without a parent item, so the ingest meets a
// standalone top-level attachment.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 25mm)
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")

#align(center)[
  #text(size: 14pt)[The signal code of the Kestrel Islands] \
  #v(4pt)
  #text(size: 9pt, style: "italic")[Offprint, harbour office Torvig, 2018]
]
#v(12pt)

Six flags are in use: grey for a sighted mail boat, blue for a requested pilot,
red for a closed harbour, white for a doctor needed on the island, black for a
death in the settlement, and yellow when fresh water runs short.

A flag is valid only while it is hoisted — lowering it is the only way to take
a message back. Two flags on one mast are read from the top down, and red over
anything else means the harbour is closed and the rest has to wait. White over
black is forbidden. A flag at half mast means "understood, help is on the way".
