// Source of tests/fixtures/zotero/storage/KESTREL09/tide-office-cover.pdf — a
// one-page cover stub, not the document it stands for. The extraction is
// complete; the source is thin. That is a third state, distinct from "a scan
// with no text layer", and the ingest has to tell them apart (BUG-004).
// Deliberately under 200 characters of text.
// Generated by scripts/make_testdata.py.
#set page(paper: "a4", margin: 25mm)
#set text(font: "Libertinus Serif", size: 10pt, lang: "en")

#align(center + horizon)[
  #text(size: 16pt)[Tide office of Fenmouth] \
  #v(6pt)
  #text(size: 11pt)[Annual report 2021] \
  #v(4pt)
  #text(size: 9pt, style: "italic")[Cover sheet]
]
